[formatter.rust]
command = "cargo"
options = ["fmt", "--"]
includes = [ "*.rs" ]

[formatter.tasks]
command = "just"
options = ["--fmt", "-f"]
includes = ["justfile"]

[formatter.release]
command = "just"
options = ["--fmt", "-f"]
includes = ["dist/justfile"]


